/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wanghongjun_ndk_opencv_demo_01_opencv_OpenCVHelper */

#ifndef _Included_com_example_wanghongjun_ndk_opencv_demo_01_opencv_OpenCVHelper
#define _Included_com_example_wanghongjun_ndk_opencv_demo_01_opencv_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wanghongjun_ndk_opencv_demo_01_opencv_OpenCVHelper
 * Method:    test
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wanghongjun_ndk_1opencv_1demo_101_opencv_OpenCVHelper_test
  (JNIEnv *, jclass);

/*
 * Class:     com_example_wanghongjun_ndk_opencv_demo_01_opencv_OpenCVHelper
 * Method:    image2Gray
 * Signature: (II[I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_wanghongjun_ndk_1opencv_1demo_101_opencv_OpenCVHelper_image2Gray
  (JNIEnv *, jclass, jint, jint, jintArray);

#ifdef __cplusplus
}
#endif
#endif
